site_name: Documentació DavidFS - ITIC
site_url: https://davidfs-itic.github.io/davidfs-itic
site_dir: ./site
site_author: David F
plugins:
    - search
    - awesome-pages
markdown_extensions:
  - admonition
  - pymdownx.details      # For collapsible admonitions
  - pymdownx.superfences  # For nested content
  - toc:
      permalink: true
      toc_depth: 3
# Tema
theme:
  name: material
  language: ca
  #locale: ca
  palette:
      - scheme: default
        primary: teal
        accent: indigo
        toggle:
            icon: material/toggle-switch-off-outline
            name: Canviar a mode fosc
      - scheme: slate
        primary: teal
        accent: indigo
        toggle:
            icon: material/toggle-switch
            name: Canviar a mode clar
  features:
  - navigation.instant
  - navigation.expand
  - navigation.tabs
#  - navigation.sections
#  - navigation.path
#  - search.suggest
#  //El toc.integrate està de moment desactivat perquè fa que no es vegi el toc a la dreta de la pàgina
#  - toc.integrate

nav:
    - Inici: index.md             # Aquesta serà la primera pàgina
    - Android:  
      - Introducció a Android: Android/index.md
      - Activities: Android/activities.md
      - Fragments: Android/fragments.md
      - Llenguatge Kotlin: 
        - Introducció a Kotlin: Android/Kotlin/index.md
        - Variables i Constants: Android/Kotlin/variables.md
        - Funcions: Android/Kotlin/funcions.md
        - Classes i Objectes: Android/Kotlin/classesobjectes.md
        - Null Safety: Android/Kotlin/nullsafety.md
        - Funcions d'extensió: Android/Kotlin/fextensio.md
        - LiveData: Android/Kotlin/livedata.md
        - Coroutines: Android/Kotlin/coroutines.md
        - Anotadors: Android/Kotlin/anotadors.md
      - Interficies:
        - Introducció a les Interficies: Android/Interficies/index.md
        - Layout en Activities: Android/Interficies/layoutactivities.md
        - Layouts: Android/Interficies/layouts.md
        - Temes i Estils: Android/Interficies/temes.md
        - VieweBinding: Android/Interficies/viewbinding.md        
        - Bottom Menu: Android/Interficies/bottommenu.md
        - Appbar: Android/Interficies/appbar.md
        - Toolbar: Android/Interficies/toolbar.md
        - Navigation Drawer: Android/Interficies/drawermenu.md
        - Dialegs: Android/Interficies/dialegs.md
        - RecyclerView: Android/Interficies/recyclerview.md
        - Recyclerview filtrat: Android/Interficies/recyclerviewfilter.md
        - RecyclerView amb searchview: Android/Interficies/recyclersearchview.md
        - Menús: Android/Interficies/menus.md
        - Splash Screen: Android/Interficies/splashscreen.md
        - Voice Recognition: Android/Interficies/voicerecognition.md
      - Arquitectura:
        - Introducció a l'Arquitectura: Android/Arquitectura/index.md
        - ViewModel: Android/Arquitectura/viewmodel.md
        - Application ViewModel: Android/Arquitectura/applicationviewmodel.md
        - Observer: Android/Arquitectura/observer.md
        - Dommini (Repositori) i Dades: Android/Arquitectura/repositori.md
        - Inversió de Dependències: Android/Arquitectura/inversiodependencies.md
        - Patró Factory: Android/Arquitectura/factory.md
        - Exemple DIP recycler: Android/Arquitectura/recyclerinversio.md 
        - Principis SOLID: Android/Arquitectura/solid.md
      - Llibreries:
        - Introducció a les Llibreries: Android/Llibreries/index.md
        - Retrofit: Android/Llibreries/retrofit.md
        - MPAndroidChart: Android/Llibreries/mpandroidchart.md
        - Firebase:
          - Introducció a Firebase: Android/Firebase/index.md
          - Setup de Firebase a Android: Android/Firebase/fbsetup.md
          - Firestore: Android/Firebase/firestore.md
          # - Autenticació: Android/Firebase/autenticacio.md
          # - Firestore: Android/Firebase/firestore.md
          # - FireCloud Messaging: Android/Firebase/fcm.md
    - Exemples de codi Android: Exemples/index.md
    - Unity:
      - Reconeixement de Veu a Unity: Unity/recveu.md
    - Arduino:
      - Instal·lació de l'IDE d'Arduino: Arduino/instalacio.md
    # - Referències: referencies.md
    - IoT: 
      - Introducció a l'IoT: IoT/index.md
      - Guia Oracle Cloud: IoT/oracle.md
    #   - Introducció a l'IoT: IoT/introduccio.md
    #   - Dispositius IoT:
    #     - Sensors IoT: IoT/sensors.md
    #     - Raspberry Pi: IoT/raspberrypi.md
    #     - Arduino IoT: IoT/arduinoiot.md
    #   - Backends IoT:
    #     - InfluxDB: IoT/influxdb.md
    #     - Node-RED: IoT/nodered.md
    #     - ThingsBoard: IoT/thingsboard.md
    #     - Grafana: IoT/grafana.md
    #     - MQTT: IoT/mqtt.md
    #     - ChirpStack: IoT/chirpstack.md
    #   - Protocols IoT:
    #     - HTTP/HTTPS: IoT/http.md
    #     - MQTT: IoT/mqttprotocol.md
    #     - CoAP: IoT/coap.md
    #     - LoRaWAN: IoT/lorawan.md
    #     - Sigfox: IoT/sigfox.md
    #     - NB-IoT: IoT/nbiot.md
    #     - Zigbee: IoT/zigbee.md
    #   - IIoT (Internet Industrial de les Coses):
    #     - Introducció a l'IIoT: IoT/iiot/introduccio.md
    #     - Protocols Industrials: IoT/iiot/protocols.md
    #     - Plataformes IIoT: IoT/iiot/plataformes.md
    #     - Casos d'Ús IIoT: IoT/iiot/casos.md
    #   - Seguretat IoT: IoT/seguretat.md