site_name: Documentació DavidFS - ITIC
site_url: https://davidfs-itic.github.io/davidfs-itic
site_dir: ./site
site_author: David F
plugins:
    - search
    - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details      # For collapsible admonitions
  - pymdownx.superfences  # For nested content
# Tema
theme:
  name: material
  language: ca
  #locale: ca
  palette:
      - scheme: default
        primary: teal
        accent: indigo
        toggle:
            icon: material/toggle-switch-off-outline
            name: Canviar a mode fosc
      - scheme: slate
        primary: teal
        accent: indigo
        toggle:
            icon: material/toggle-switch
            name: Canviar a mode clar
  features:
  - navigation.instant
  - navigation.expand
  - navigation.tabs
#  - navigation.sections
#  - navigation.path
#  - search.suggest
#  //El toc.integrate està de moment desactivat perquè fa que no es vegi el toc a la dreta de la pàgina
#  - toc.integrate

nav:
    - Inici: index.md             # Aquesta serà la primera pàgina
    - Android:  
      - Introducció a Android: Android/index.md
      - Activities: Android/activities.md
      - Fragments: Android/fragments.md
      - Arquitectura:
        - Introducció a l'Arquitectura: Android/Arquitectura/index.md
        - VieweBinding: Android/Arquitectura/viewbinding.md
        - ViewModel: Android/Arquitectura/viewmodel.md
        - LiveData: Android/Arquitectura/livedata.md
        - Observer: Android/Arquitectura/observer.md
        - Repositori: Android/Arquitectura/repositori.md
        - Inversió de Dependències: Android/Arquitectura/inversiodependencies.md
        - Exemple DIP recycler: Android/Arquitectura/recyclerinversio.md
      - Interficies: 
        - Layouts: Android/Interficies/layouts.md
        - Temes i Estils: Android/Interficies/temes.md
        - Appbar: Android/Interficies/appbar.md
        - Toolbar: Android/Interficies/toolbar.md
        - Bottom Menu: Android/Interficies/bottommenu.md
        - Navigation Drawer: Android/Interficies/drawermenu.md
        - Dialegs: Android/Interficies/dialegs.md
        - RecyclerView: Android/Interficies/recyclerview.md
        - Menús: Android/Interficies/menus.md
        - Splash Screen: Android/Interficies/splashscreen.md
      - Llenguatge Kotlin: 
        - Introducció a Kotlin: Android/Kotlin/introduccio.md
        - Variables i Constats: Android/Kotlin/variables.md
        - Funcions: Android/Kotlin/funcions.md
        - Classes i Objectes: Android/Kotlin/classesobjectes.md
        - Null Safety: Android/Kotlin/nullsafety.md
        - Collections: Android/Kotlin/collections.md
        - Funcions d'extensió: Android/Kotlin/fextensio.md
        - Coroutines: Android/Kotlin/coroutines.md
        - Flow: Android/Kotlin/flow.md
      - Bases de Dades:
        - Room: Android/BasesDeDades/room.md
        - SharedPreferences: Android/BasesDeDades/sharedpreferences.md
      - Firebase:
        - Introducció a Firebase: Android/Firebase/introduccio.md
        - Setup de Firebase a Android: Android/Firebase/fbsetup.md
        - Autenticació: Android/Firebase/autenticacio.md
        - Firestore: Android/Firebase/firestore.md
        - Storage: Android/Firebase/storage.md
        - FireCloud Messaging: Android/Firebase/fcm.md
    - Exemples de codi Android: Exemples/index.md
    - Arduino: Arduino/index.md
    - Referències: referencies.md